### ISSUE TITLE
Image Assets

### ISSUE THREAD

**Issue by Da-Colon** [decent-dao/decent-ui#4]
Any Icon or image Assets needed for Decent Design Tokens

**Comment by Da-Colon** [comment]
Decide on with define Icons versus action icons

**Comment by xraystyle1980** [comment]
@Da-Colon can we update this ticket to reflect assets needed for Decent DS and not Fractal? (in light of todays conversation about creating Decent DS as the base and then theming Fractal on top)

**Comment by Da-Colon** [comment]
@xraystyle1980 description updated
