### ISSUE TITLE
Add `space-mono` google font

### ISSUE THREAD

**Issue by dacebt** [decent-dao/decent-ui#95]

**Comment by dacebt** [comment]
@decentdao/design I didn't write any notes here, is this still a thing?

**Comment by xraystyle1980** [comment]
We're using Space Mono as our mono-spaced "terminal" font (see expanded accordion for executable code)
https://fonts.google.com/specimen/Space+Mono

Is this task just to load the font into the app?

![image](https://github.com/decentdao/decent-ui/assets/18615633/b6d16ddd-3860-4432-a313-17b3d866f013)

**Comment by dacebt** [comment]
This was closed, with https://github.com/decentdao/decent-ui/pull/98
